name: Smoke Test
on:
  pull_request: {}
  push:
    branches:
      - main

permissions: read-all

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          fetch-depth: '0'
      - name: Build
        run: |
          make build
      - name: Test
        run: |
          make test
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
        with:
          # renovate: datasource=docker depName=golangci/golangci-lint
          version: v2.12.2
          skip-cache: true
          args: "--verbose --modules-download-mode=vendor"
